{
    "name": "POS Sale Channel",
    "summary": "Manage and track POS transactions by sales channel",
    "version": "17.0.1.1.0",
    "category": "Point of Sale",
    "license": "LGPL-3",
    "depends": ["point_of_sale", "pos_restaurant"],
    "data": [
        "security/ir.model.access.csv",
        "data/pos_sale_channel_data.xml",
        "views/pos_sale_channel_views.xml",
        "views/pos_config_views.xml",
        "views/pos_order_views.xml",
        "views/pos_online_checker_recap_views.xml",
    ],
    "assets": {
        "point_of_sale._assets_pos": [
            "pos_sale_channel/static/src/app/store/order_sale_channel.js",
            "pos_sale_channel/static/src/app/store/online_order_checker_store.js",
            "pos_sale_channel/static/src/app/navbar/online_checker_recap_navbar.js",
            "pos_sale_channel/static/src/app/navbar/online_checker_recap_navbar.xml",
            "pos_sale_channel/static/src/app/screens/online_order_checker/online_order_checker_screen.js",
            "pos_sale_channel/static/src/app/screens/online_order_checker/online_order_checker_screen.xml",
            "pos_sale_channel/static/src/app/screens/online_order_checker/online_order_checker_ticket_button.js",
            "pos_sale_channel/static/src/app/screens/online_order_checker/online_order_checker_ticket_button.xml",
            "pos_sale_channel/static/src/app/screens/receipt_screen/online_order_checker_receipt.js",
            "pos_sale_channel/static/src/app/screens/receipt_screen/online_order_checker_receipt.xml",
            "pos_sale_channel/static/src/app/screens/receipt_screen/receipt_header_sale_channel.xml",
            "pos_sale_channel/static/src/app/screens/product_screen/control_buttons/online_checker_recap_button/online_checker_recap_button.js",
            "pos_sale_channel/static/src/app/screens/product_screen/control_buttons/online_checker_recap_button/online_checker_recap_button.xml",
            "pos_sale_channel/static/src/app/screens/product_screen/control_buttons/sale_channel_button/sale_channel_button.js",
            "pos_sale_channel/static/src/app/screens/product_screen/control_buttons/sale_channel_button/sale_channel_button.xml",
            "pos_sale_channel/static/src/app/screens/product_screen/control_buttons/sale_channel_button/sale_channel_line_button.js",
            "pos_sale_channel/static/src/app/screens/product_screen/control_buttons/sale_channel_button/sale_channel_line_button.xml",
        ],
    },
    "installable": True,
    "application": False,
}
