{
    "name": "POS Membership",
    "summary": "Membership, deposit wallet, rewards, and portal for POS",
    "version": "17.0.1.0.0",
    "category": "Point of Sale",
    "license": "LGPL-3",
    "depends": [
        "point_of_sale",
        "pos_loyalty",
        "portal",
        "website",
        "mail",
    ],
    "data": [
        "security/ir.model.access.csv",
        "views/res_config_settings_views.xml",
        "views/res_partner_views.xml",
        "views/pos_payment_method_views.xml",
        "views/membership_ledger_views.xml",
        "views/daily_reward_views.xml",
        "views/loyalty_program_views.xml",
        "views/member_portal_templates.xml",
    ],
    "assets": {
        "point_of_sale._assets_pos": [
            "pos_membership/static/src/app/store/pos_membership_store.js",
            "pos_membership/static/src/app/store/order_membership.js",
            "pos_membership/static/src/app/store/loyalty_membership.js",
            "pos_membership/static/src/app/store/barcode_reader_membership.js",
            "pos_membership/static/src/app/components/customer_button/customer_button.js",
            "pos_membership/static/src/app/components/membership_badge/membership_badge.js",
            "pos_membership/static/src/app/components/membership_badge/membership_badge.xml",
            "pos_membership/static/src/app/control_buttons/claim_daily_reward/claim_daily_reward_button.js",
            "pos_membership/static/src/app/control_buttons/claim_daily_reward/claim_daily_reward_button.xml",
            "pos_membership/static/src/xml/customer_button.xml",
            "pos_membership/static/src/xml/payment_screen.xml",
            "pos_membership/static/src/xml/order_receipt.xml",
            "pos_membership/static/src/scss/pos_membership.scss",
        ],
        "web.assets_frontend": [
            "pos_membership/static/src/lib/barcode_renderer.js",
            "pos_membership/static/src/portal/member_portal.js",
            "pos_membership/static/src/scss/member_portal.scss",
        ],
    },
    "installable": True,
    "application": False,
}
