"""
server.py — Helpdesk MCP Server
────────────────────────────────
Exposes Odoo helpdesk data and actions as MCP tools so that Claude
(in Cowork or Claude Code) can:

  • Browse open tickets and their AI analysis
  • Read full development plans generated by the Claude AI module
  • Post messages or internal notes to ticket chatter
  • Trigger re-analysis
  • Update ticket stage / priority / assignee

Usage (stdio — for Claude Code / Cowork):
    python server.py

Usage (SSE — for remote/HTTP access):
    MCP_TRANSPORT=sse MCP_PORT=8765 python server.py

Configure via .env  (copy .env.example → .env and fill in your values).
"""

import json
import os
from html import unescape
from re import sub as re_sub

from dotenv import load_dotenv
from mcp.server.fastmcp import FastMCP

from odoo_client import OdooClient

load_dotenv()

# ── Initialise ────────────────────────────────────────────────────────────────
mcp = FastMCP(
    "Odoo Helpdesk",
    description=(
        "Tools for reading and managing Odoo 17 helpdesk tickets, "
        "including Claude AI triage results and developer guidance plans."
    ),
)
odoo = OdooClient()


# ── Utility ───────────────────────────────────────────────────────────────────

def _html_to_text(html: str) -> str:
    """Very lightweight HTML → plain text for MCP responses."""
    if not html:
        return ""
    text = re_sub(r"<br\s*/?>", "\n", html, flags=0)
    text = re_sub(r"<p[^>]*>", "\n", text)
    text = re_sub(r"</p>", "\n", text)
    text = re_sub(r"<li[^>]*>", "\n  • ", text)
    text = re_sub(r"<h[1-6][^>]*>", "\n## ", text)
    text = re_sub(r"</h[1-6]>", "\n", text)
    text = re_sub(r"<th[^>]*>", " | ", text)
    text = re_sub(r"<td[^>]*>", " | ", text)
    text = re_sub(r"<[^>]+>", "", text)   # strip remaining tags
    text = unescape(text)
    # Collapse excess blank lines
    text = re_sub(r"\n{3,}", "\n\n", text)
    return text.strip()


def _format_ticket_summary(t: dict) -> str:
    """Format a ticket dict as a readable summary string."""
    ai_status = t.get("ai_status") or "not analysed"
    classification = t.get("ai_classification") or "—"
    partner = (
        (t.get("partner_id") or [None, "Unknown"])[1]
        if isinstance(t.get("partner_id"), list)
        else t.get("partner_name", "Unknown")
    )
    team = (
        (t.get("team_id") or [None, "—"])[1]
        if isinstance(t.get("team_id"), list)
        else "—"
    )
    stage = (
        (t.get("stage_id") or [None, "—"])[1]
        if isinstance(t.get("stage_id"), list)
        else "—"
    )
    priority_labels = {"0": "Normal", "1": "High", "2": "Very High", "3": "Critical"}
    priority = priority_labels.get(str(t.get("priority", "0")), "Normal")

    return (
        f"#{t.get('number', '?')}  {t.get('name', 'No title')}\n"
        f"  Partner: {partner}  |  Team: {team}  |  Stage: {stage}  |  Priority: {priority}\n"
        f"  AI: {ai_status}  |  Classification: {classification}"
        + (f"  |  Summary: {t.get('ai_summary', '')}" if t.get("ai_summary") else "")
    )


# ═════════════════════════════════════════════════════════════════════════════
# MCP TOOLS
# ═════════════════════════════════════════════════════════════════════════════

@mcp.tool()
def list_tickets(
    status_filter: str = "open",
    ai_status: str = "",
    team_name: str = "",
    limit: int = 20,
) -> str:
    """
    List helpdesk tickets with optional filters.

    Args:
        status_filter: "open" (default), "closed", or "all"
        ai_status:     Filter by AI status: pending / answered / dev_plan /
                       failed / manual / processing / "" (all)
        team_name:     Filter by team name (partial match, case-insensitive)
        limit:         Max tickets to return (default 20)

    Returns a formatted list of tickets with their AI analysis status.
    """
    domain: list = []

    if status_filter == "open":
        domain.append(["closed", "=", False])
    elif status_filter == "closed":
        domain.append(["closed", "=", True])

    if ai_status:
        domain.append(["ai_status", "=", ai_status])

    if team_name:
        domain.append(["team_id.name", "ilike", team_name])

    tickets = odoo.search_tickets(domain=domain, limit=limit)

    if not tickets:
        return "No tickets found matching your criteria."

    lines = [f"Found {len(tickets)} ticket(s):\n"]
    for t in tickets:
        lines.append(_format_ticket_summary(t))
        lines.append("")

    return "\n".join(lines)


@mcp.tool()
def get_ticket(ticket_ref: str) -> str:
    """
    Get full details of a specific ticket, including AI analysis and description.

    Args:
        ticket_ref: Ticket ID (integer) or ticket number like "HD00042"

    Returns full ticket details including AI classification, summary,
    and a preview of the description.
    """
    if ticket_ref.isdigit():
        ticket = odoo.get_ticket(int(ticket_ref))
    else:
        ticket = odoo.get_ticket_by_number(ticket_ref.strip())

    if not ticket:
        return f"Ticket '{ticket_ref}' not found."

    partner = (
        (ticket.get("partner_id") or [None, "Unknown"])[1]
        if isinstance(ticket.get("partner_id"), list)
        else ticket.get("partner_name", "Unknown")
    )
    team = (
        (ticket.get("team_id") or [None, "—"])[1]
        if isinstance(ticket.get("team_id"), list)
        else "—"
    )
    stage = (
        (ticket.get("stage_id") or [None, "—"])[1]
        if isinstance(ticket.get("stage_id"), list)
        else "—"
    )
    user = (
        (ticket.get("user_id") or [None, "Unassigned"])[1]
        if isinstance(ticket.get("user_id"), list)
        else "Unassigned"
    )
    category = (
        (ticket.get("category_id") or [None, "—"])[1]
        if isinstance(ticket.get("category_id"), list)
        else "—"
    )
    priority_labels = {"0": "Normal", "1": "High", "2": "Very High", "3": "Critical"}

    description_text = _html_to_text(ticket.get("description", "") or "")

    output = [
        f"═══ TICKET {ticket.get('number')} ═══",
        f"Title:          {ticket.get('name')}",
        f"Partner:        {partner}",
        f"Team:           {team}",
        f"Assigned to:    {user}",
        f"Stage:          {stage}",
        f"Category:       {category}",
        f"Priority:       {priority_labels.get(str(ticket.get('priority', '0')), 'Normal')}",
        f"Created:        {ticket.get('create_date', '—')}",
        "",
        "── DESCRIPTION ──────────────────────────────",
        description_text[:1500] + ("..." if len(description_text) > 1500 else ""),
        "",
        "── AI ANALYSIS ──────────────────────────────",
        f"Status:         {ticket.get('ai_status') or 'Not analysed'}",
        f"Classification: {ticket.get('ai_classification') or '—'}",
        f"Confidence:     {(ticket.get('ai_confidence') or 0) * 100:.0f}%",
        f"Summary:        {ticket.get('ai_summary') or '—'}",
        f"Affected mods:  {ticket.get('ai_affected_modules') or '—'}",
        f"Est. hours:     {ticket.get('ai_estimated_hours') or '—'}",
        f"Analysed at:    {ticket.get('ai_analyzed_date') or '—'}",
    ]

    return "\n".join(output)


@mcp.tool()
def get_development_plan(ticket_ref: str) -> str:
    """
    Retrieve Claude's AI-generated development plan for a bug or feature ticket.

    Use this when you (as a developer) want the full plan to guide your
    implementation work. The plan includes problem analysis, proposed solution,
    files to modify, testing checklist, and risk notes.

    Args:
        ticket_ref: Ticket ID or number (e.g. "HD00042")

    Returns the development plan in readable plain text.
    """
    if ticket_ref.isdigit():
        ticket = odoo.get_ticket(int(ticket_ref))
    else:
        ticket = odoo.get_ticket_by_number(ticket_ref.strip())

    if not ticket:
        return f"Ticket '{ticket_ref}' not found."

    if ticket.get("ai_classification") not in ("bug", "feature"):
        return (
            f"Ticket {ticket.get('number')} is classified as "
            f"'{ticket.get('ai_classification') or 'unclassified'}'. "
            "Development plans are only generated for Bug Reports and Feature Requests."
        )

    dev_plan_html = ticket.get("ai_dev_plan", "") or ""
    if not dev_plan_html:
        return (
            f"No development plan found for ticket {ticket.get('number')}. "
            "Run AI analysis first (trigger_ai_analysis) or click "
            "'🤖 Analyse with Claude' in the Odoo form."
        )

    header = (
        f"╔══════════════════════════════════════════════════╗\n"
        f"║  DEVELOPMENT PLAN — {ticket.get('number')}  \n"
        f"║  {ticket.get('name', '')[:60]}\n"
        f"║  Est. {ticket.get('ai_estimated_hours') or '?'} hours  "
        f"| Modules: {ticket.get('ai_affected_modules') or '—'}\n"
        f"╚══════════════════════════════════════════════════╝\n\n"
    )

    return header + _html_to_text(dev_plan_html)


@mcp.tool()
def get_customer_response(ticket_ref: str) -> str:
    """
    Retrieve Claude's AI-generated customer response for a configuration query ticket.

    Args:
        ticket_ref: Ticket ID or number (e.g. "HD00042")

    Returns the customer-facing response text ready for review / sending.
    """
    if ticket_ref.isdigit():
        ticket = odoo.get_ticket(int(ticket_ref))
    else:
        ticket = odoo.get_ticket_by_number(ticket_ref.strip())

    if not ticket:
        return f"Ticket '{ticket_ref}' not found."

    if ticket.get("ai_classification") != "configuration":
        return (
            f"Ticket {ticket.get('number')} is classified as "
            f"'{ticket.get('ai_classification') or 'unclassified'}', "
            "not a configuration query. Customer responses are only generated for "
            "CONFIGURATION_QUERY tickets."
        )

    response_html = ticket.get("ai_response", "") or ""
    if not response_html:
        return f"No customer response found for ticket {ticket.get('number')}."

    return _html_to_text(response_html)


@mcp.tool()
def post_message_to_ticket(
    ticket_ref: str,
    message: str,
    internal: bool = False,
) -> str:
    """
    Post a message or internal note to a ticket's chatter.

    Args:
        ticket_ref: Ticket ID or number
        message:    Plain text or basic HTML message body
        internal:   True = internal note (agents only), False = public reply to customer

    Returns confirmation with the new message ID.
    """
    if ticket_ref.isdigit():
        ticket = odoo.get_ticket(int(ticket_ref))
    else:
        ticket = odoo.get_ticket_by_number(ticket_ref.strip())

    if not ticket:
        return f"Ticket '{ticket_ref}' not found."

    msg_id = odoo.post_message(ticket["id"], message, internal=internal)
    note_type = "internal note" if internal else "public reply"
    return (
        f"✅ Posted {note_type} to ticket {ticket.get('number')} "
        f"(message ID: {msg_id})."
    )


@mcp.tool()
def get_ticket_messages(ticket_ref: str, limit: int = 10) -> str:
    """
    Retrieve the most recent chatter messages for a ticket.

    Args:
        ticket_ref: Ticket ID or number
        limit:      Number of messages to return (default 10)

    Returns a formatted list of chatter messages newest-first.
    """
    if ticket_ref.isdigit():
        ticket = odoo.get_ticket(int(ticket_ref))
    else:
        ticket = odoo.get_ticket_by_number(ticket_ref.strip())

    if not ticket:
        return f"Ticket '{ticket_ref}' not found."

    messages = odoo.get_ticket_messages(ticket["id"], limit=limit)
    if not messages:
        return f"No messages found for ticket {ticket.get('number')}."

    lines = [f"Last {len(messages)} message(s) for ticket {ticket.get('number')}:\n"]
    for msg in messages:
        author = (
            (msg.get("author_id") or [None, "Unknown"])[1]
            if isinstance(msg.get("author_id"), list)
            else "Unknown"
        )
        subtype = (
            (msg.get("subtype_id") or [None, ""])[1]
            if isinstance(msg.get("subtype_id"), list)
            else ""
        )
        is_note = "Internal Note" in (subtype or "")
        label = "🔒 Internal" if is_note else "💬 Public"
        body_text = _html_to_text(msg.get("body", ""))[:500]
        lines.append(
            f"[{msg.get('date', '—')}]  {label}  — {author}\n"
            f"  {body_text}\n"
        )

    return "\n".join(lines)


@mcp.tool()
def update_ticket(
    ticket_ref: str,
    stage_name: str = "",
    priority: str = "",
    assignee_login: str = "",
    note: str = "",
) -> str:
    """
    Update a ticket's stage, priority, or assignee, and optionally post a note.

    Args:
        ticket_ref:     Ticket ID or number
        stage_name:     Name of the target stage (e.g. "In Progress", "Resolved")
        priority:       "0" Normal, "1" High, "2" Very High, "3" Critical
        assignee_login: Odoo login of the agent to assign
        note:           Optional internal note to post after the update

    Returns a summary of what was changed.
    """
    if ticket_ref.isdigit():
        ticket = odoo.get_ticket(int(ticket_ref))
    else:
        ticket = odoo.get_ticket_by_number(ticket_ref.strip())

    if not ticket:
        return f"Ticket '{ticket_ref}' not found."

    ticket_id = ticket["id"]
    vals: dict = {}
    changes: list[str] = []

    if stage_name:
        stages = odoo.list_stages()
        match = next(
            (s for s in stages if s["name"].lower() == stage_name.lower()), None
        )
        if not match:
            available = ", ".join(s["name"] for s in stages)
            return (
                f"Stage '{stage_name}' not found. "
                f"Available stages: {available}"
            )
        vals["stage_id"] = match["id"]
        changes.append(f"stage → {match['name']}")

    if priority in ("0", "1", "2", "3"):
        vals["priority"] = priority
        labels = {"0": "Normal", "1": "High", "2": "Very High", "3": "Critical"}
        changes.append(f"priority → {labels[priority]}")

    if assignee_login:
        users = odoo.call(
            "res.users",
            "search_read",
            [[["login", "=", assignee_login]]],
            {"fields": ["id", "name"], "limit": 1},
        )
        if not users:
            return f"User with login '{assignee_login}' not found."
        vals["user_id"] = users[0]["id"]
        changes.append(f"assigned → {users[0]['name']}")

    if vals:
        odoo.update_ticket(ticket_id, vals)

    if note:
        odoo.post_message(ticket_id, note, internal=True)
        changes.append("internal note posted")

    if not changes:
        return "No changes requested."

    return (
        f"✅ Ticket {ticket.get('number')} updated: "
        + ", ".join(changes) + "."
    )


@mcp.tool()
def trigger_ai_analysis(ticket_ref: str) -> str:
    """
    Queue a ticket for immediate Claude AI analysis.

    Sets the ticket's AI status to 'pending' so the cron picks it up
    within 5 minutes. For instant analysis, use the 'Analyse with Claude'
    button directly on the Odoo ticket form.

    Args:
        ticket_ref: Ticket ID or number

    Returns confirmation.
    """
    if ticket_ref.isdigit():
        ticket = odoo.get_ticket(int(ticket_ref))
    else:
        ticket = odoo.get_ticket_by_number(ticket_ref.strip())

    if not ticket:
        return f"Ticket '{ticket_ref}' not found."

    odoo.trigger_ai_analysis(ticket["id"])
    return (
        f"✅ Ticket {ticket.get('number')} queued for AI analysis. "
        "It will be processed within the next 5 minutes by the cron job. "
        "For immediate analysis, click '🤖 Analyse with Claude' on the "
        "Odoo ticket form."
    )


@mcp.tool()
def list_dev_plan_tickets(limit: int = 20) -> str:
    """
    List all open tickets that have an AI-generated development plan ready.

    These are tickets classified as Bug Report or Feature Request where
    Claude has already generated a development guidance plan.
    Use get_development_plan(ticket_ref) to read the full plan for any ticket.

    Args:
        limit: Max tickets to return (default 20)

    Returns a formatted list of tickets with dev plans awaiting implementation.
    """
    tickets = odoo.search_tickets(
        domain=[["ai_status", "=", "dev_plan"], ["closed", "=", False]],
        limit=limit,
        order="priority desc, create_date asc",
    )

    if not tickets:
        return "No open tickets with ready development plans found."

    lines = [
        f"📋 {len(tickets)} ticket(s) with Claude dev plans awaiting implementation:\n"
    ]
    for t in tickets:
        est = t.get("ai_estimated_hours")
        hours_str = f"  Est. {est:.1f}h" if est else ""
        modules_str = (
            f"  Modules: {t.get('ai_affected_modules')}"
            if t.get("ai_affected_modules")
            else ""
        )
        summary_str = (
            f"\n  Summary: {t.get('ai_summary')}" if t.get("ai_summary") else ""
        )
        lines.append(
            f"  • {t.get('number')}  {t.get('name')}{hours_str}{modules_str}"
            f"{summary_str}"
        )
        lines.append("")

    return "\n".join(lines)


@mcp.tool()
def get_ai_dashboard() -> str:
    """
    Show a summary dashboard of Claude AI analysis activity across all tickets.

    Returns counts by AI status, total analysed, and pending items
    requiring developer attention.
    """
    stats = odoo.get_ai_stats()
    teams = odoo.list_teams()
    ai_teams = [t for t in teams if t.get("ai_enabled")]

    lines = [
        "╔══════════════════════════════════════╗",
        "║   Helpdesk AI Dashboard              ║",
        "╚══════════════════════════════════════╝",
        "",
        f"Teams with Claude AI enabled: {len(ai_teams)}",
        "  " + ", ".join(t["name"] for t in ai_teams) if ai_teams else "  (none)",
        "",
        "── Ticket AI Status Counts ──────────────",
        f"  ⏳ Pending analysis:    {stats.get('pending', 0)}",
        f"  ⚙️  Processing:          {stats.get('processing', 0)}",
        f"  ✅ Auto-answered:       {stats.get('answered', 0)}",
        f"  📋 Dev plan ready:      {stats.get('dev_plan', 0)}",
        f"  👀 Needs manual review: {stats.get('manual', 0)}",
        f"  ❌ Failed:              {stats.get('failed', 0)}",
        f"  ─────────────────────────────────────",
        f"  Total analysed:         {stats.get('total_analysed', 0)}",
        "",
        "Use list_dev_plan_tickets() to see tickets awaiting developer implementation.",
    ]

    return "\n".join(lines)


@mcp.tool()
def list_teams() -> str:
    """
    List all helpdesk teams and their Claude AI configuration.

    Returns team names, AI enabled status, and whether auto-reply is on.
    """
    teams = odoo.list_teams()
    if not teams:
        return "No helpdesk teams found."

    lines = [f"Found {len(teams)} team(s):\n"]
    for team in teams:
        ai_flag = "✅ AI ON" if team.get("ai_enabled") else "⬜ AI OFF"
        reply_flag = "  | auto-reply ✅" if team.get("ai_auto_reply") else ""
        context_preview = ""
        if team.get("ai_project_context"):
            ctx = team["ai_project_context"][:80]
            context_preview = f"\n    Context: {ctx}..."
        lines.append(f"  [{team['id']}] {team['name']}  {ai_flag}{reply_flag}{context_preview}")

    return "\n".join(lines)


# ═════════════════════════════════════════════════════════════════════════════
# MCP RESOURCES
# ═════════════════════════════════════════════════════════════════════════════

@mcp.resource("helpdesk://overview")
def resource_overview() -> str:
    """High-level summary of the helpdesk system and AI status."""
    return get_ai_dashboard()


@mcp.resource("helpdesk://pending-dev-plans")
def resource_pending_dev_plans() -> str:
    """List of all tickets with ready development plans awaiting implementation."""
    return list_dev_plan_tickets(limit=50)


# ═════════════════════════════════════════════════════════════════════════════
# Entry point
# ═════════════════════════════════════════════════════════════════════════════

if __name__ == "__main__":
    transport = os.getenv("MCP_TRANSPORT", "stdio")

    if transport == "sse":
        port = int(os.getenv("MCP_PORT", "8765"))
        print(f"Starting Helpdesk MCP server (SSE) on port {port}…")
        mcp.run(transport="sse", port=port)
    else:
        # Default: stdio (for Claude Code / Cowork integration)
        mcp.run(transport="stdio")
