import json
import logging
import time

import requests

from odoo import _, api, fields, models
from odoo.exceptions import UserError
from odoo.tools import html2plaintext

_logger = logging.getLogger(__name__)

# ── Claude API constants ───────────────────────────────────────────────────────
ANTHROPIC_API_URL = "https://api.anthropic.com/v1/messages"
ANTHROPIC_VERSION = "2023-06-01"
DEFAULT_MODEL = "claude-opus-4-6"
MAX_TOKENS = 4096
REQUEST_TIMEOUT = 90  # seconds

# ── Classification mapping ────────────────────────────────────────────────────
CLASSIFICATION_MAP = {
    "CONFIGURATION_QUERY": "configuration",
    "BUG_REPORT": "bug",
    "FEATURE_REQUEST": "feature",
    "OTHER": "other",
}

PRIORITY_MAP = {
    "low": "0",
    "medium": "1",
    "high": "2",
    "urgent": "3",
}


class HelpdeskTicket(models.Model):
    _inherit = "helpdesk.ticket"

    # ── AI status & classification fields ────────────────────────────────────
    ai_status = fields.Selection(
        selection=[
            ("pending", "Pending Analysis"),
            ("processing", "Processing"),
            ("answered", "Answered by AI"),
            ("dev_plan", "Dev Plan Generated"),
            ("manual", "Needs Manual Review"),
            ("failed", "AI Failed"),
        ],
        string="AI Status",
        index=True,
        tracking=True,
        copy=False,
    )
    ai_classification = fields.Selection(
        selection=[
            ("configuration", "Configuration Query"),
            ("bug", "Bug Report"),
            ("feature", "Feature Request"),
            ("other", "Other"),
        ],
        string="AI Classification",
        copy=False,
    )
    ai_confidence = fields.Float(
        string="AI Confidence",
        digits=(3, 2),
        copy=False,
    )
    ai_analyzed_date = fields.Datetime(
        string="Last Analysed",
        copy=False,
    )
    ai_summary = fields.Char(
        string="AI Summary",
        copy=False,
        help="One-line ticket summary generated by Claude.",
    )
    ai_affected_modules = fields.Char(
        string="Affected Modules",
        copy=False,
        help="Odoo modules identified by Claude as relevant to this ticket.",
    )
    ai_estimated_hours = fields.Float(
        string="Estimated Hours (AI)",
        copy=False,
        digits=(5, 1),
    )

    # ── AI output fields ──────────────────────────────────────────────────────
    ai_response = fields.Html(
        string="AI Customer Response",
        copy=False,
        sanitize_style=True,
        help="For CONFIGURATION_QUERY: Claude's answer formatted for the customer.",
    )
    ai_dev_plan = fields.Html(
        string="Development Plan",
        copy=False,
        sanitize_style=True,
        help="For BUG_REPORT / FEATURE_REQUEST: Claude's structured development plan.",
    )
    ai_log_ids = fields.One2many(
        comodel_name="helpdesk.ai.log",
        inverse_name="ticket_id",
        string="AI Log",
        copy=False,
    )
    ai_log_count = fields.Integer(
        string="AI Analyses",
        compute="_compute_ai_log_count",
    )

    # ── Computed helpers ──────────────────────────────────────────────────────
    @api.depends("ai_log_ids")
    def _compute_ai_log_count(self):
        for ticket in self:
            ticket.ai_log_count = len(ticket.ai_log_ids)

    # ═════════════════════════════════════════════════════════════════════════
    # ORM overrides
    # ═════════════════════════════════════════════════════════════════════════

    @api.model_create_multi
    def create(self, vals_list):
        tickets = super().create(vals_list)
        for ticket in tickets:
            if ticket.team_id.ai_enabled:
                ticket.ai_status = "pending"
        return tickets

    # ═════════════════════════════════════════════════════════════════════════
    # Cron entry point
    # ═════════════════════════════════════════════════════════════════════════

    @api.model
    def _cron_analyze_pending_tickets(self, batch_size=10):
        """Process up to batch_size pending tickets per cron run."""
        pending = self.search(
            [("ai_status", "=", "pending"), ("team_id.ai_enabled", "=", True)],
            limit=batch_size,
            order="create_date asc",
        )
        _logger.info("Helpdesk AI cron: processing %d pending tickets", len(pending))
        for ticket in pending:
            try:
                ticket.with_context(ai_trigger="auto")._analyze_with_claude()
            except Exception as exc:
                _logger.exception(
                    "Helpdesk AI cron: failed to analyse ticket %s: %s",
                    ticket.number,
                    exc,
                )
                ticket.sudo().write({"ai_status": "failed"})

    # ═════════════════════════════════════════════════════════════════════════
    # Core AI analysis
    # ═════════════════════════════════════════════════════════════════════════

    def _get_api_key(self):
        key = (
            self.env["ir.config_parameter"]
            .sudo()
            .get_param("helpdesk_claude.api_key", default="")
        )
        if not key:
            raise UserError(
                _(
                    "Claude API key is not configured. "
                    "Please set it in Settings → Helpdesk → Claude AI."
                )
            )
        return key

    def _get_model(self):
        return (
            self.env["ir.config_parameter"]
            .sudo()
            .get_param("helpdesk_claude.model", default=DEFAULT_MODEL)
        )

    def _build_system_prompt(self):
        """Build the Claude system prompt, injecting team-level project context."""
        team = self.team_id
        project_context = team.ai_project_context or (
            "No additional project context provided."
        )
        installed_modules = team.ai_installed_modules or (
            "helpdesk_mgmt (OCA v17.0.1.10.3)"
        )

        return f"""You are an expert Odoo 17 Community Edition support engineer and \
developer embedded inside a helpdesk ticketing system.

Your job is to:
1. Read the incoming support ticket (title + description).
2. Classify it into exactly one of: CONFIGURATION_QUERY, BUG_REPORT, \
FEATURE_REQUEST, or OTHER.
3. Depending on the classification, generate either:
   - A professional, helpful customer-facing HTML response (CONFIGURATION_QUERY)
   - A detailed HTML-formatted developer guidance plan (BUG_REPORT / FEATURE_REQUEST)

━━━━━━━━━━━━━━━━━━━━━━━━━━━━
PROJECT CONTEXT
━━━━━━━━━━━━━━━━━━━━━━━━━━━━
{project_context}

KEY INSTALLED MODULES:
{installed_modules}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━
CLASSIFICATION RULES
━━━━━━━━━━━━━━━━━━━━━━━━━━━━
CONFIGURATION_QUERY:
  The customer is asking how to use or configure an existing Odoo feature.
  No code or database changes are required — only settings or user guidance.
  Examples: "How do I enable automatic email replies?", "Where is the SLA setting?"

BUG_REPORT:
  Something that previously worked is now broken, or behaves in a way that \
contradicts expected / documented behaviour.
  Examples: "The ticket stage doesn't advance when customer replies", \
"Email notification not sent on close"

FEATURE_REQUEST:
  The customer wants new functionality that doesn't exist yet.
  Examples: "Can we add a WhatsApp notification?", "I need a custom field for \
ticket severity"

OTHER:
  General inquiry, out-of-scope, incomplete description, or not actionable.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━
RESPONSE FORMAT
━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Return ONLY a single valid JSON object — no markdown fences, no preamble, \
no trailing text.

{{
  "classification": "CONFIGURATION_QUERY | BUG_REPORT | FEATURE_REQUEST | OTHER",
  "confidence": <float 0.0–1.0>,
  "summary": "<one sentence, under 120 chars, describing the ticket>",
  "priority_suggestion": "low | medium | high | urgent",
  "affected_modules": ["<odoo_module_name>", ...],
  "estimated_hours": <float | null — only for BUG_REPORT / FEATURE_REQUEST>,
  "response": "<HTML string — only for CONFIGURATION_QUERY: professional \
customer-facing answer>",
  "dev_plan": "<HTML string — only for BUG_REPORT / FEATURE_REQUEST: \
detailed developer guidance plan>"
}}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━
HTML FORMATTING RULES
━━━━━━━━━━━━━━━━━━━━━━━━━━━━
For `response` (customer-facing):
  - Use <p>, <ul><li>, <strong>, <em>, <br/> only.
  - Start with "Dear Customer," and end with "Best regards,\\nSupport Team".
  - Be concise, clear, and professional.

For `dev_plan` (developer-facing):
  Use this exact HTML structure:

  <h2>🎯 Classification & Scope</h2>
  <table> ... summary table: Classification / Priority / Affected Modules / \
Est. Hours </table>

  <h2>📋 Problem Analysis</h2>
  <p>...</p>

  <h2>🔍 Root Cause (for bugs) / Design Rationale (for features)</h2>
  <p>...</p>

  <h2>💡 Proposed Solution</h2>
  <p>Step-by-step approach...</p>

  <h2>📁 Files to Create / Modify</h2>
  <table>
    <thead><tr><th>File</th><th>Action</th><th>What to change</th></tr></thead>
    <tbody>...</tbody>
  </table>

  <h2>🧪 Testing Checklist</h2>
  <ul>
    <li>☐ Test case 1</li>
    ...
  </ul>

  <h2>⚠️ Risks & Considerations</h2>
  <ul>...</ul>

  Keep the HTML clean — no inline styles, no JavaScript.
"""

    def _build_ticket_message(self):
        """Format ticket data as the user turn for Claude."""
        description_text = html2plaintext(self.description or "").strip()
        category = self.category_id.name if self.category_id else "Not set"
        channel = self.channel_id.name if hasattr(self, "channel_id") and self.channel_id else "Not set"
        tag_names = ", ".join(self.tag_ids.mapped("name")) if self.tag_ids else "None"
        priority_labels = dict(self._fields["priority"].selection)
        priority_label = priority_labels.get(self.priority, "Normal")

        return f"""SUPPORT TICKET
─────────────────────────────
Ticket #:     {self.number}
Title:        {self.name}
Category:     {category}
Channel:      {channel}
Tags:         {tag_names}
Priority:     {priority_label}
Partner:      {self.partner_name or (self.partner_id.name if self.partner_id else 'Unknown')}
─────────────────────────────
DESCRIPTION:

{description_text or '(No description provided)'}
─────────────────────────────
Please analyse this ticket and respond with the JSON object."""

    def _call_anthropic_api(self, system_prompt, user_message):
        """
        Low-level HTTP call to Anthropic Messages API.
        Returns (response_text, usage_dict, duration_ms).
        """
        api_key = self._get_api_key()
        model = self._get_model()

        headers = {
            "x-api-key": api_key,
            "anthropic-version": ANTHROPIC_VERSION,
            "content-type": "application/json",
        }
        payload = {
            "model": model,
            "max_tokens": MAX_TOKENS,
            "system": system_prompt,
            "messages": [{"role": "user", "content": user_message}],
        }

        start = time.time()
        try:
            resp = requests.post(
                ANTHROPIC_API_URL,
                headers=headers,
                json=payload,
                timeout=REQUEST_TIMEOUT,
            )
            duration_ms = int((time.time() - start) * 1000)
            resp.raise_for_status()
        except requests.exceptions.Timeout:
            raise UserError(
                _("Claude API request timed out after %d seconds.") % REQUEST_TIMEOUT
            )
        except requests.exceptions.HTTPError as exc:
            _logger.error(
                "Claude API HTTP %s: %s", exc.response.status_code, exc.response.text
            )
            raise UserError(
                _("Claude API error (%s): %s")
                % (exc.response.status_code, exc.response.text[:300])
            )
        except requests.exceptions.ConnectionError:
            raise UserError(
                _("Could not connect to Claude API. Check your network / firewall.")
            )

        body = resp.json()
        text = body.get("content", [{}])[0].get("text", "")
        usage = body.get("usage", {})
        return text, usage, duration_ms, model

    def _parse_claude_response(self, raw_text):
        """Parse JSON from Claude's response, tolerating minor formatting issues."""
        text = raw_text.strip()
        # Strip accidental markdown fences
        if text.startswith("```"):
            text = text.split("```")[1]
            if text.startswith("json"):
                text = text[4:]
        if text.endswith("```"):
            text = text.rsplit("```", 1)[0]
        try:
            return json.loads(text.strip())
        except json.JSONDecodeError as exc:
            _logger.error(
                "Could not parse Claude JSON response: %s\nRaw: %s", exc, raw_text[:500]
            )
            raise UserError(
                _(
                    "Claude returned an unexpected format. "
                    "Check the AI log for details."
                )
            )

    def _analyze_with_claude(self):
        """
        Orchestrate the full AI analysis cycle for a single ticket.
        Called by the cron (async) and the manual button (sync).
        """
        self.ensure_one()
        trigger = self.env.context.get("ai_trigger", "manual")

        # Mark as processing so the cron doesn't pick it up again
        self.sudo().write({"ai_status": "processing"})
        self.env.cr.commit()  # flush status update before the API call

        log_vals = {
            "ticket_id": self.id,
            "trigger": trigger,
        }

        try:
            system_prompt = self._build_system_prompt()
            user_message = self._build_ticket_message()

            raw_text, usage, duration_ms, model_used = self._call_anthropic_api(
                system_prompt, user_message
            )
            data = self._parse_claude_response(raw_text)

            classification = data.get("classification", "OTHER")
            odoo_classification = CLASSIFICATION_MAP.get(classification, "other")
            confidence = float(data.get("confidence", 0.0))
            summary = data.get("summary", "")
            priority_suggestion = data.get("priority_suggestion", "")
            affected_modules = data.get("affected_modules", [])
            estimated_hours = data.get("estimated_hours") or 0.0

            # Determine new status
            if classification == "CONFIGURATION_QUERY":
                new_status = "answered"
            elif classification in ("BUG_REPORT", "FEATURE_REQUEST"):
                new_status = "dev_plan"
            else:
                new_status = "manual"

            # Build write vals
            write_vals = {
                "ai_status": new_status,
                "ai_classification": odoo_classification,
                "ai_confidence": confidence,
                "ai_summary": summary[:250] if summary else "",
                "ai_affected_modules": ", ".join(affected_modules) if affected_modules else "",
                "ai_estimated_hours": estimated_hours,
                "ai_analyzed_date": fields.Datetime.now(),
            }

            # Apply AI priority suggestion (only upgrade, never downgrade)
            if priority_suggestion:
                suggested_priority = PRIORITY_MAP.get(priority_suggestion.lower(), "")
                if suggested_priority and suggested_priority > self.priority:
                    write_vals["priority"] = suggested_priority

            if classification == "CONFIGURATION_QUERY":
                write_vals["ai_response"] = data.get("response", "")
            elif classification in ("BUG_REPORT", "FEATURE_REQUEST"):
                write_vals["ai_dev_plan"] = data.get("dev_plan", "")

            self.sudo().write(write_vals)

            # Post chatter messages
            if classification == "CONFIGURATION_QUERY" and self.team_id.ai_auto_reply:
                self._post_ai_customer_response()
            if classification in ("BUG_REPORT", "FEATURE_REQUEST") and self.team_id.ai_auto_dev_note:
                self._post_dev_plan_internal_note(classification, estimated_hours, affected_modules)

            # Log success
            log_vals.update(
                {
                    "classification": classification,
                    "confidence": confidence,
                    "model_used": model_used,
                    "prompt_tokens": usage.get("input_tokens", 0),
                    "completion_tokens": usage.get("output_tokens", 0),
                    "duration_ms": duration_ms,
                    "response_summary": summary,
                }
            )

        except Exception as exc:
            _logger.exception(
                "Helpdesk AI: analysis failed for ticket %s", self.number
            )
            self.sudo().write({"ai_status": "failed"})
            log_vals["error"] = str(exc)[:2000]
            raise
        finally:
            self.env["helpdesk.ai.log"].sudo().create(log_vals)

    # ─── Chatter helpers ──────────────────────────────────────────────────────

    def _post_ai_customer_response(self):
        """Post Claude's configuration answer as a public customer-facing message."""
        self.ensure_one()
        if not self.ai_response:
            return
        self.message_post(
            body=self.ai_response,
            message_type="comment",
            subtype_xmlid="mail.mt_comment",
            author_id=self.env.ref("base.partner_root").id,
        )
        _logger.info(
            "Helpdesk AI: posted customer response for ticket %s", self.number
        )

    def _post_dev_plan_internal_note(self, classification, estimated_hours, affected_modules):
        """Post Claude's dev plan as an internal note visible only to agents."""
        self.ensure_one()
        if not self.ai_dev_plan:
            return
        label = "Bug Report" if classification == "BUG_REPORT" else "Feature Request"
        hours_text = (
            f" — Estimated effort: <strong>{estimated_hours:.1f} hours</strong>"
            if estimated_hours
            else ""
        )
        modules_text = (
            f"<br/><em>Affected modules: {', '.join(affected_modules)}</em>"
            if affected_modules
            else ""
        )
        header = (
            f"<p><strong>🤖 Claude AI — Development Plan ({label})</strong>"
            f"{hours_text}{modules_text}</p><hr/>"
        )
        self.message_post(
            body=header + self.ai_dev_plan,
            message_type="comment",
            subtype_xmlid="mail.mt_note",  # internal note
            author_id=self.env.ref("base.partner_root").id,
        )
        _logger.info(
            "Helpdesk AI: posted dev plan internal note for ticket %s", self.number
        )

    # ═════════════════════════════════════════════════════════════════════════
    # Button actions
    # ═════════════════════════════════════════════════════════════════════════

    def action_analyze_with_claude(self):
        """Manual trigger: analyse the current ticket immediately (synchronous)."""
        self.ensure_one()
        if not self.team_id.ai_enabled:
            raise UserError(
                _(
                    "Claude AI is not enabled for team '%s'. "
                    "Enable it in Helpdesk > Configuration > Teams."
                )
                % self.team_id.name
            )
        self.with_context(ai_trigger="manual")._analyze_with_claude()
        return {
            "type": "ir.actions.client",
            "tag": "display_notification",
            "params": {
                "title": _("Claude AI Analysis Complete"),
                "message": _(
                    "Ticket classified as: %s (confidence: %.0f%%)"
                )
                % (
                    dict(self._fields["ai_classification"].selection or []).get(
                        self.ai_classification, self.ai_classification or "—"
                    ),
                    (self.ai_confidence or 0) * 100,
                ),
                "type": "success",
                "sticky": False,
            },
        }

    def action_reset_ai_pending(self):
        """Reset AI status to pending so the cron re-analyses this ticket."""
        self.write({"ai_status": "pending"})

    def action_view_ai_log(self):
        """Open the AI log for this ticket."""
        self.ensure_one()
        return {
            "type": "ir.actions.act_window",
            "name": _("AI Analysis Log"),
            "res_model": "helpdesk.ai.log",
            "view_mode": "list,form",
            "domain": [("ticket_id", "=", self.id)],
            "target": "current",
        }
