[options]
addons_path = /mnt/extra-addons/custom,/mnt/extra-addons/v17,/mnt/extra-addons/v17/project,/mnt/extra-addons/v17/helpdesk,/mnt/extra-addons/v17/website,/mnt/extra-addons/v17/knowledge,/mnt/extra-addons/v17/web,/mnt/extra-addons/v17/management-system,/mnt/extra-addons/v17/timesheet
admin_passwd = $pbkdf2-sha512$600000$CIFwjhEiRKjVOqeU0loLgQ$..IgXXBNjd1/hL9/4zvc7.BRZgOTaRW2xbKulQSY2Dz5AbXPxkRFwHxsdmvqPpJKA5q0v.9UjDevBgKu.BDa/w
db_host = db
db_user = odoo
db_password = odoo
dbfilter = ^ksv17-dev$
log_level = debug
logfile = /var/log/odoo/odoo.log
proxy_mode = True

# cd addons/custom/<module_name>
# git status
# git add .
# git commit -m "your message"
# git push
