{
    "name": "Helpdesk Custom Demo",
    "version": "17.0.1.0.0",
    "category": "After-Sales",
    "summary": "Sample helpdesk data for showcasing OCA helpdesk features",
    "author": "Custom",
    "license": "LGPL-3",
    "depends": [
        "helpdesk_mgmt",
        "helpdesk_type",
        "helpdesk_mgmt_sla",
        "helpdesk_mgmt_template",
        "helpdesk_mgmt_assign_method",
        "helpdesk_mgmt_rating",
        "helpdesk_ticket_close_inactive",
        "helpdesk_mgmt_merge",
        "helpdesk_ticket_related",
        "helpdesk_mgmt_project",
        "helpdesk_mgmt_sale",
        "helpdesk_mgmt_crm",
        "helpdesk_mgmt_activity",
        "helpdesk_ticket_partner_response",
        "helpdesk_mgmt_timesheet",
        "helpdesk_mgmt_stage_validation",
        "helpdesk_portal_restriction",
        "helpdesk_timesheet_time_type",
    ],
    "post_init_hook": "post_init_hook",
    "installable": True,
    "application": False,
    "auto_install": False,
}
