import json
import re

from odoo.tests import HttpCase, tagged


@tagged("post_install", "-at_install")
class TestHelpdeskCustomApi(HttpCase):
    @classmethod
    def setUpClass(cls):
        super().setUpClass()
        cls.env["ir.config_parameter"].sudo().set_param("helpdesk_custom_api.enabled", "True")
        cls.env["ir.config_parameter"].sudo().set_param(
            "helpdesk_custom_api.token", "test-helpdesk-api-token"
        )
        cls.headers = {"Authorization": "Bearer test-helpdesk-api-token"}

        cls.team = cls.env["helpdesk.ticket.team"].search([], limit=1)
        cls.category = cls.env["helpdesk.ticket.category"].search([], limit=1)
        cls.ticket_type = cls.env["helpdesk.ticket.type"].search([], limit=1)
        cls.partner = cls.env["res.partner"].create(
            {
                "name": "API Test Contact",
                "email": "api-test-contact@example.com",
            }
        )
        cls.ticket = cls.env["helpdesk.ticket"].create(
            {
                "name": "API Test Base Ticket",
                "description": "<p>Base ticket for API test.</p>",
                "team_id": cls.team.id if cls.team else False,
                "partner_id": cls.partner.id,
                "category_id": cls.category.id if cls.category else False,
                "type_id": cls.ticket_type.id if cls.ticket_type else False,
            }
        )

    def _json_open(self, path, data=None):
        payload = json.dumps(data or {})
        return self.url_open(
            path,
            data=payload,
            headers={**self.headers, "Content-Type": "application/json"},
        )

    def _get_csrf(self, html):
        match = re.search(r'name="csrf_token"\s+value="([^"]+)"', html)
        return match.group(1) if match else ""

    def test_health_endpoint(self):
        response = self.url_open("/api/helpdesk/v1/health", headers=self.headers)
        self.assertEqual(response.status_code, 200)
        payload = response.json()
        self.assertTrue(payload.get("ok"))
        self.assertEqual(payload.get("data", {}).get("service"), "helpdesk_custom_api")

    def test_reply_validation_error(self):
        response = self._json_open(f"/api/helpdesk/v1/tickets/{self.ticket.id}/reply", data={})
        self.assertEqual(response.status_code, 400)
        payload = response.json()
        self.assertFalse(payload.get("ok"))
        self.assertEqual(payload.get("error", {}).get("code"), "validation_error")

    def test_create_close_and_reopen_flow(self):
        create_payload = {
            "name": "API Test Ticket for Close/Reopen",
            "description": "Ticket generated by automated test.",
            "team_id": self.team.id if self.team else False,
            "partner_id": self.partner.id,
            "category_id": self.category.id if self.category else False,
            "type_id": self.ticket_type.id if self.ticket_type else False,
            "priority": "2",
        }
        response = self._json_open("/api/helpdesk/v1/tickets/create", data=create_payload)
        self.assertEqual(response.status_code, 201)
        created = response.json()["data"]
        ticket_id = created["id"]

        response = self._json_open(
            f"/api/helpdesk/v1/tickets/{ticket_id}/reply",
            data={"message": "Automated API test reply."},
        )
        self.assertEqual(response.status_code, 200)
        self.assertTrue(response.json().get("ok"))

        response = self._json_open(f"/api/helpdesk/v1/tickets/{ticket_id}/close", data={})
        self.assertEqual(response.status_code, 200)
        close_payload = response.json()
        self.assertTrue(close_payload.get("ok"))
        self.assertTrue(close_payload.get("data", {}).get("closed"))

        public_url = close_payload.get("data", {}).get("public_portal_url")
        self.assertTrue(public_url)
        public_token = public_url.split("/helpdesk/track/", 1)[1].split("?", 1)[0]
        self.assertTrue(public_token)

        response = self.url_open(f"/helpdesk/track/{public_token}")
        self.assertEqual(response.status_code, 200)
        csrf_token = self._get_csrf(response.text)
        self.assertTrue(csrf_token)

        response = self.url_open(
            f"/helpdesk/track/{public_token}/reopen",
            data={
                "csrf_token": csrf_token,
                "reopen_reason": "issue_not_resolved",
                "reopen_detail": "Automated test reopen flow.",
                "confirm_reopen": "1",
            },
            allow_redirects=True,
        )
        self.assertEqual(response.status_code, 200)
        self.assertIn("reopen_success=1", response.url)
