from . import daily_claim_log
from . import daily_free_product_config
from . import loyalty_program
from . import membership_deposit_ledger
from . import membership_point_ledger
from . import pos_order
from . import pos_payment_method
from . import pos_session
from . import res_company
from . import res_config_settings
from . import res_partner
